#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    q=w=e=0
    r=len(arr)
    for i in arr:
        if i<0:
            q+=1
        elif i>0:
            w+=1
        else:
            e+=1
    print(f"{w/r:.6f}")
    print(f"{q/r:.6f}")
    print(f"{e/r:.6f}")
    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
